version: "3.8"

services:
  calculator:
    build: .
    ports:
      - "3111:3111"  # External:Internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3111/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s